### ISSUE TITLE
aws_iam_policy_attachment of AWS managed policies overrides existing attachements

### ISSUE THREAD

**Issue by MoerphyK** [Olgoetz/terraform-aws-tfc-state-backup#1]
### CloudWatch policy attachment
resource "aws_iam_policy_attachment" "cw" {
  name       = "${aws_iam_role.this.name}-cw-attachment"
  roles      = [aws_iam_role.this.name]
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
}

### EC2 policy policy attachment
resource "aws_iam_policy_attachment" "ec2" {
  count      = var.create_lambda_vpc_config ? 1 : 0
  name       = "${aws_iam_role.this.name}-ec2-attachment"
  roles      = [aws_iam_role.this.name]
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
}

## Issue
If the Terraform script that consumes this module is executed, while one or both managed AWS policies 
"arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
or
"arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
are already attached to a role, which is not part of the running Terraform script, Terraform tries to remove the managed policy from all roles that are not part of the current state.

Example:
Team A created the lambda service role : "LambdaBasicRoleA" with the managed policy "AWSLambdaBasicExecutionRole".

Team B working on the same AWS account now consumes the tfc-state-backup module will receive following Terraform plan:

```
module.statebackup[0].aws_iam_policy_attachment.cw
groups :[ ]
id : "TerraformStateBackup-Lambda-Role-cw-attachment"
name : "TerraformStateBackup-Lambda-Role-cw-attachment"
policy_arn : "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
update
roles :
[
  delete "LambdaBasicRoleA"
  create "TerraformStateBackup-Lambda-Role"
]
users : [ ]
```

**Comment by Olgoetz** [comment]
fixed with https://github.com/Olgoetz/terraform-aws-tfc-state-backup/pull/3
